blog/urls.py
from django.urls import path 

#Vista Generica -> para utilizar un archivo como si fuera una vista o view
from django.views.generic import TemplateView

from .views import *

app_name = 'blog'


urlpatterns = [  
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('celebridades', listar_Celebridad, name='listar_Celebridad'),
    path('<uuid:pub>/',ver_Celebridad, name='ver_Celebridad'),
    path('categoria/<int:categoria>/', ver_Celebridad_categoria, name='ver_Celebridad_categoria')
]     

liliaa/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls'))
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User

import uuid 

class Categoria(models.Model):
    descripcion = models.CharField(max_length=60,
                                    help_text='Descripcion de la Categoria')
    autor = models.ForeignKey(User,
                                on_delete=models.PROTECT,
                                help_text='Seleccione el autor de la categoria')
    
    def __str__(self):
        return self.descripcion


class Celebridad(models.Model):
    id = models.UUIDField(primary_key= True, editable=False, default=uuid.uuid4)
    titulo = models.CharField(max_length=200,
                                help_text='Escriba el titulo de la publicacion')
    contenido = models.TextField(max_length=20000,
                                 help_text='Escriba el contenido de la publicacion')
    autor = models.ForeignKey(User,
                                on_delete=models.PROTECT,
                                help_text='Seleccione el autor de la categoria')
    f_pub = models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Publicacion')
   
    categorias = models.ManyToManyField(Categoria,
                                        help_text='Seleccione las categorias')
    
    def __str__(self):
        return self.titulo

    class Meta:
        verbose_name="lugar"
        verbose_name_plural = "lugar"
        ordering = ['-f_pub']



        

        
         
 

    

blog/views.py
from django.shortcuts import render

from .models import *


def listar_Celebridad(request):
    news = Celebridad.objects.all().order_by('-f_pub')
    return render(request, './post/index.html', {'Celebridad':Celebridad})

def ver_Celebridad(request, pub):
    celebridad = Celebridad.objects.get(id = pub)
    return render(request, './post/ver.html', {'Celebridad':celebridad})

def ver_Celebridad_categoria(request, categoria):
    categoria = Categoria.objects.get(id = categoria)
    return render(request, './post/index.html', {'categoria':categoria})
 

blog/templates/base.html
<!DOCTYPE html>
<html lang="es">
<html>
  <head>
    
     
    <title>{% block titulo %}{% endblock  %}</title>
     <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">  
    <link rel="icon" type="" href="https://lh3.googleusercontent.com/proxy/E9kdScbXEVpPF1RtOFJVeDfaTGTq5gorm1F6mJ_Z6MVASyNw1L0ivkW-zX-fjmEzmiMEfWtqM_LWeREbpvGM77DudtdxEmuvfoaiNrEqU6Jl8rzZlAkZQ971EIhGOFaw39L4DHrhKg">
  </head>
  <body  bgcolor="#e0e0e0 ">
    
     
      

    <!-- browser o explorador -->
     
      
   
        
      <nav class="nav-extended grey darken-4 white-tex">
        <div class="nav-wrapper">
          <a href="{% url 'blog:home' %}" class="brand-logo"><font face="Lucida Handwriting">Gastronomia</a></font>
        
          <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
          <ul id="nav-mobile" class="right hide-on-med-and-down">

            <li><a href="{% url 'blog:ver_Celebridad_categoria' 2 %}"><font face="Lucida Handwriting"> Europa</a></li></font>
            <li><a href="{% url 'blog:ver_Celebridad_categoria' 3 %}"><font face="Lucida Handwriting">America</a></li></font>
            <li><a href="{% url 'blog:ver_Celebridad_categoria' 5 %}"><font face="Lucida Handwriting">Asia</a></li></font>
            <li><a href="{% url 'blog:ver_Celebridad_categoria' 6 %}"><font face="Lucida Handwriting">Africa</a></li></font>

           </ul>
        </div>
        <div class="nav-content">
          <ul class="tabs tabs-transparent">
            <li class="tab"><a class="active" href="#test1"> creador</a></li>
            <li class="tab"><a  href="#test2">Asignacion</a></li>
            <li class="tab "><a href="#test3">Tema</a></li>
            <li class="tab"><a href="#test4">Mensaje</a></li>
          </ul>
        </div>
      </nav>
    
      <ul class="sidenav" id="mobile-demo">
        <li><a href=""></a></li>
        <li><a href=""></a></li>
        <li><a href=""></a></li>
      </ul>
    
      <div id="test1" class="col s12">Lilia Michelle Urbina Murillo.</div>
      <div id="test2" class="col s12">este sitio es creado y formado en la clase de programacionIV.  </div>
      <div id="test3" class="col s12">sibre Gastronomia en estos cuatro continentes.</div>
      <div id="test4" class="col s12">La alimentación ha sido siempre un aspecto crucial para la especie humana. El modo en que obtenemos alimentos de la naturaleza condiciona cómo somos, cómo vivimos y cómo nos relacionamos.

        Por supuesto, comer ha sido siempre una condición necesaria para permanecer vivos. Sin embargo, el acto de comer tiene su parte de goce. El mundo de la cocina y el arte de comer bien ha ido desarrollando
         una mirada cultural hacia la alimentación y la gastronomía propia de cada lugar.</div>


   
   
   <div class="parallax-container">
     <div class="parallax">
       <img src="https://dam.ngenespanol.com/wp-content/uploads/2018/11/5-gastronomia-paises-mundo.png" alt="">
     </div>
   </div>

   
  <div class="container" style="padding-botton:2em;">

        {% block cuerpo %}
        
        {% endblock %}
  </div>
  
  
  
<div class="parallax-container">
    <div class="parallax">
        <img src="https://www.fundacionibercaja.es/public/pub/img/china-transformada_45563.jpg" alt="">
    </div>
</div>  


<footer class="page-footer grey darken-4">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="grey darken-4 white-text">El Mundo de la Gastronomia.</h5>
        <p class="grey-text text-lighten-4">La alimentación ha sido siempre un aspecto crucial para la especie humana. El modo en que obtenemos alimentos de la naturaleza condiciona cómo somos, cómo vivimos y cómo nos relacionamos.

          Por supuesto, comer ha sido siempre una condición necesaria para permanecer vivos. Sin embargo, el acto de comer tiene su parte de goce. El mundo de la cocina y el arte de comer bien ha ido desarrollando
           una mirada cultural hacia la alimentación y la gastronomía propia de cada lugar.Gracias por visitar este sitio, esperamos regreses y recomiendes nuestra pagina.</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="grey darken-4 white-text">Links a redes sociales.</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="https://www.instagram.com/?hl=es-la">Gastronomia INSTAGRAM</a></li>
          <li><a class="grey-text text-lighten-3" href="https://web.facebook.com/?_rdc=1&_rdr">Gastronomia FACEBOOK</a></li>
          <li><a class="grey-text text-lighten-3" href="https://www.youtube.com/watch?v=nHgNwwOLLTM">Gastronomia YOUTUBE</a></li>
          <li><a class="grey-text text-lighten-3" href="https://mail.google.com/mail/u/0/#inbox">Email</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
      Gastronomia mundial &copy; Lilia Michelle Urbina Clase de programacionIV
    <a class="grey-text text-lighten-4 right" href="https://mail.google.com/mail/u/0/#sent">creador</a>
    </div>
  </div>
</footer>

</body>
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script async src="https://static.addtoany.com/menu/page.js"></script>
    <script>
      document.addEventListener('DOMContentLoaded', function() {
              M.AutoInit();
              });
    </script>
    <script>
      document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('.slider');
    var instances = M.Slider.init(elems, );
  });
    </script>


    </html>

    

blog/templates/post/index.html
{% extends "base.html" %}

{% block titulo %}Gastronomia Mundial{% endblock  %}

{% block cuerpo %}
    {% if categoria %}

        <h1>Gastronomia {{ categoria.descripcion }}</h1>
        {% for new in categoria.celebridad_set.all %}
            <div>
                
                <a href="{% url 'blog:ver_Celebridad' new.id %}">
                    <h2  align="center" class=" teal-text text-darken-2 z-depth-1">{{ new.titulo }}</h2>
                </a>
                <p>
                    {{ new.contenido|truncatechars:250 }} <br>
                    {{ new.autor.get_full_name }} publicado {{ new.f_pub}}
                    {for categoria in new.categorias.all% }
                        <a href="{% url 'blog:ver_Celebridad' new.id %}" class="white-tex">
                            {{ categoria.descripcion }}
                        </a>
                 {% endfor %}
                </p>
            </div> 
            
         
        
       {% else %}

    {% for new in news %}
        <div>
            <h2 class="white-text text-darken-2 z-depth-1">><a  href="{% url 'blog:ver_Celebridad' new.id %}"></a></h2>
            <p>
                {{ new.contenido|truncatechars:250 }} <br>
                {{ new.autor.get_full_name }} publicado {{ new.f_pub}}
                {for categoria in new categorias.all% }
                <a href="{% url 'blog:ver_Celebridad' categoria.id %}" class="whithe text">
                    {{ categoria.descripcion }}   
            </p>
        </div>
     
      
    {% endfor %}
        
    {% endif %}
    
{% endblock  %}

blog/templates/post/ver.html
{% extends 'base.html' %}

{% block titulo %} {{ Celebridad.titulo|truncatechars:30 }} Gastronomia|by lilia {% endblock %}

{% block cuerpo %}
 
    <h1>{{ Celebridad.titulo }}<div class="white-tex"></div></h1>
    <div class="white-text text-darken-2"></div>
    <p align="justify">
      {{ Celebridad.contenido }}
  
      
  <img align="center" class="materialboxed" data-caption="rr " width="250" src="https://corbuse.edu.mx/blog/wp-content/uploads/2019/09/CORBUSE-De-los-cursos-a-la-carrera-de-gastronomia-lo-ideal-para-ser-chef.jpg">
          
    </p>    
        {{ Celebridad.autor.get_full_name }} Compartir: {{ Celebridad.f_pub }}
        <div class="a2a_kit a2a_kit_size_32 a2a_default_style">  {% endblock %}
          <div class="container">
            <!-- (p>lorem)*20 (código a usar si tienes instalada la extensión emmet)-->
          </div>
        
          <div class="social">
            <a href="#"><img src="img/facebook.png" alt="facebook"></a>
            <a href="#"><img src="img/youtube.png" alt="youtube"></a>
            <a href="#"><img src="img/linkedin.png" alt="linkedin"></a>
            <a href="#"><img src="img/instagram.png" alt="instagram"></a>
          </div>
<div>
    <a href="https://www.addtoany.com/share#url=http%3A%2F%2F127.0.0.1%3A8000%2F&amp;title=" target="_blank"><img src="https://static.addtoany.com/buttons/a2a.svg" width="32" height="32" style="background-color:royalblue"></a>
    <a href="https://www.addtoany.com/add_to/facebook?linkurl=http%3A%2F%2F127.0.0.1%3A8000%2F&amp;linkname=" target="_blank"><img src="https://static.addtoany.com/buttons/facebook.svg" width="32" height="32" style="background-color:royalblue"></a>
    <a href="https://www.addtoany.com/add_to/twitter?linkurl=http%3A%2F%2F127.0.0.1%3A8000%2F&amp;linkname=" target="_blank"><img src="https://static.addtoany.com/buttons/twitter.svg" width="32" height="32" style="background-color:royalblue"></a>
    <a href="https://www.addtoany.com/add_to/email?linkurl=http%3A%2F%2F127.0.0.1%3A8000%2F&amp;linkname=" target="_blank"><img src="https://static.addtoany.com/buttons/email.svg" width="32" height="32" style="background-color:royalblue"></a>
    </div>
  </div>
  